### ISSUE TITLE
Documentation for timestamping

### ISSUE THREAD

**Issue by imZack** [Azure/iot-central-batch-telemetry-with-python#1]
Not sure if the question belongs to this repo.

There are `iothub-app-iothub-creation-time-utc` and `iothub-creation-time-utc` for timestamping purposes when you send telemetry data in a batch way.

1. https://github.com/iot-for-all/iot-central-batch-telemetry-with-python/blob/main/batch.py#L161-L168
2. https://feedback.azure.com/forums/911455-azure-iot-central/suggestions/35197819-device-originated-timestamp

Does anyone know which one we should use? And where it's been documented?

**Comment by firedog1024** [comment]
You should use 'iothub-creation-time-utc' in the message property to override the hub ingestion time of messages sent.  

The 'iothub-app-iothub-creation-time-utc' is specific to the batch send protocol used where system properties are prefixed with 'iothub-app-' within the batch.

Unfortunately the documentation around this is a bit sketchy we are working to correct this and to improve the documentation on system message properties.

**Comment by imZack** [comment]
Gotcha, so those two have different usage.
Look forward to having the documentation once it's ready. Thank you for answering!
